version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Use the default Next.js port 3000 if NEXT_PUBLIC_PORT is not set
      - "${NEXT_PUBLIC_PORT:-3000}:3000"
    # Removed depends_on: - redis
    # Removed environment: - REDIS_URL=redis://redis:6379
    restart: unless-stopped

# Removed redis and webscraper services
# Removed volumes definition as it's no longer needed for redis
