version: '3.8'

services:
  scraper:
    build: .
    depends_on:
      - redis
    environment:
      - PROXY_USERNAME=${PROXY_USERNAME}
      - PROXY_PASSWORD=${PROXY_PASSWORD}
      - REDIS_ADDR=redis:6379
    volumes:
      - .:/app
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
